% Produced by CVXGEN, 2020-02-24 13:45:01 -0500.
% CVXGEN is Copyright (C) 2006-2017 Jacob Mattingley, jem@cvxgen.com.
% The code in this file is Copyright (C) 2006-2017 Jacob Mattingley.
% CVXGEN, or solvers produced by CVXGEN, cannot be used for commercial
% applications without prior written permission from Jacob Mattingley.

% Filename: cvxsolve.m.
% Description: Solution file, via cvx, for use with sample.m.
function [vars, status] = cvxsolve(params, settings)
A = params.A;
B = params.B;
Q = params.Q;
Q_final = params.Q_final;
R = params.R;
S = params.S;
u_max = params.u_max;
x_0 = params.x_0;
x_max = params.x_max;
if isfield(params, 'x_ref_1')
  x_ref_1 = params.x_ref_1;
elseif isfield(params, 'x_ref')
  x_ref_1 = params.x_ref{1};
else
  error 'could not find x_ref_1'
end
if isfield(params, 'x_ref_2')
  x_ref_2 = params.x_ref_2;
elseif isfield(params, 'x_ref')
  x_ref_2 = params.x_ref{2};
else
  error 'could not find x_ref_2'
end
if isfield(params, 'x_ref_3')
  x_ref_3 = params.x_ref_3;
elseif isfield(params, 'x_ref')
  x_ref_3 = params.x_ref{3};
else
  error 'could not find x_ref_3'
end
if isfield(params, 'x_ref_4')
  x_ref_4 = params.x_ref_4;
elseif isfield(params, 'x_ref')
  x_ref_4 = params.x_ref{4};
else
  error 'could not find x_ref_4'
end
if isfield(params, 'x_ref_5')
  x_ref_5 = params.x_ref_5;
elseif isfield(params, 'x_ref')
  x_ref_5 = params.x_ref{5};
else
  error 'could not find x_ref_5'
end
if isfield(params, 'x_ref_6')
  x_ref_6 = params.x_ref_6;
elseif isfield(params, 'x_ref')
  x_ref_6 = params.x_ref{6};
else
  error 'could not find x_ref_6'
end
if isfield(params, 'x_ref_7')
  x_ref_7 = params.x_ref_7;
elseif isfield(params, 'x_ref')
  x_ref_7 = params.x_ref{7};
else
  error 'could not find x_ref_7'
end
if isfield(params, 'x_ref_8')
  x_ref_8 = params.x_ref_8;
elseif isfield(params, 'x_ref')
  x_ref_8 = params.x_ref{8};
else
  error 'could not find x_ref_8'
end
if isfield(params, 'x_ref_9')
  x_ref_9 = params.x_ref_9;
elseif isfield(params, 'x_ref')
  x_ref_9 = params.x_ref{9};
else
  error 'could not find x_ref_9'
end
if isfield(params, 'x_ref_10')
  x_ref_10 = params.x_ref_10;
elseif isfield(params, 'x_ref')
  x_ref_10 = params.x_ref{10};
else
  error 'could not find x_ref_10'
end
if isfield(params, 'x_ref_11')
  x_ref_11 = params.x_ref_11;
elseif isfield(params, 'x_ref')
  x_ref_11 = params.x_ref{11};
else
  error 'could not find x_ref_11'
end
cvx_begin
  % Caution: automatically generated by cvxgen. May be incorrect.
  variable u_0(2, 1);
  variable x_1(4, 1);
  variable u_1(2, 1);
  variable x_2(4, 1);
  variable u_2(2, 1);
  variable x_3(4, 1);
  variable u_3(2, 1);
  variable x_4(4, 1);
  variable u_4(2, 1);
  variable x_5(4, 1);
  variable u_5(2, 1);
  variable x_6(4, 1);
  variable u_6(2, 1);
  variable x_7(4, 1);
  variable u_7(2, 1);
  variable x_8(4, 1);
  variable u_8(2, 1);
  variable x_9(4, 1);
  variable u_9(2, 1);
  variable x_10(4, 1);
  variable u_10(2, 1);
  variable x_11(4, 1);

  minimize(quad_form(u_0, R) + quad_form(x_1 - x_ref_1, Q) + quad_form(u_1, R) + quad_form(x_2 - x_ref_2, Q) + quad_form(u_2, R) + quad_form(x_3 - x_ref_3, Q) + quad_form(u_3, R) + quad_form(x_4 - x_ref_4, Q) + quad_form(u_4, R) + quad_form(x_5 - x_ref_5, Q) + quad_form(u_5, R) + quad_form(x_6 - x_ref_6, Q) + quad_form(u_6, R) + quad_form(x_7 - x_ref_7, Q) + quad_form(u_7, R) + quad_form(x_8 - x_ref_8, Q) + quad_form(u_8, R) + quad_form(x_9 - x_ref_9, Q) + quad_form(u_9, R) + quad_form(x_10 - x_ref_10, Q) + quad_form(u_10, R) + quad_form(x_11 - x_ref_11, Q_final));
  subject to
    x_1 == A*x_0 + B*u_0;
    x_2 == A*x_1 + B*u_1;
    x_3 == A*x_2 + B*u_2;
    x_4 == A*x_3 + B*u_3;
    x_5 == A*x_4 + B*u_4;
    x_6 == A*x_5 + B*u_5;
    x_7 == A*x_6 + B*u_6;
    x_8 == A*x_7 + B*u_7;
    x_9 == A*x_8 + B*u_8;
    x_10 == A*x_9 + B*u_9;
    x_11 == A*x_10 + B*u_10;
    abs(x_1) <= x_max;
    abs(x_2) <= x_max;
    abs(x_3) <= x_max;
    abs(x_4) <= x_max;
    abs(x_5) <= x_max;
    abs(x_6) <= x_max;
    abs(x_7) <= x_max;
    abs(x_8) <= x_max;
    abs(x_9) <= x_max;
    abs(x_10) <= x_max;
    abs(x_11) <= x_max;
    abs(u_0) <= u_max;
    abs(u_1) <= u_max;
    abs(u_2) <= u_max;
    abs(u_3) <= u_max;
    abs(u_4) <= u_max;
    abs(u_5) <= u_max;
    abs(u_6) <= u_max;
    abs(u_7) <= u_max;
    abs(u_8) <= u_max;
    abs(u_9) <= u_max;
    abs(u_10) <= u_max;
    norm(u_1 - u_0, inf) <= S;
    norm(u_2 - u_1, inf) <= S;
    norm(u_3 - u_2, inf) <= S;
    norm(u_4 - u_3, inf) <= S;
    norm(u_5 - u_4, inf) <= S;
    norm(u_6 - u_5, inf) <= S;
    norm(u_7 - u_6, inf) <= S;
    norm(u_8 - u_7, inf) <= S;
    norm(u_9 - u_8, inf) <= S;
    norm(u_10 - u_9, inf) <= S;
cvx_end
vars.u_0 = u_0;
vars.u_1 = u_1;
vars.u{1} = u_1;
vars.u_2 = u_2;
vars.u{2} = u_2;
vars.u_3 = u_3;
vars.u{3} = u_3;
vars.u_4 = u_4;
vars.u{4} = u_4;
vars.u_5 = u_5;
vars.u{5} = u_5;
vars.u_6 = u_6;
vars.u{6} = u_6;
vars.u_7 = u_7;
vars.u{7} = u_7;
vars.u_8 = u_8;
vars.u{8} = u_8;
vars.u_9 = u_9;
vars.u{9} = u_9;
vars.u_10 = u_10;
vars.u{10} = u_10;
vars.x_1 = x_1;
vars.x{1} = x_1;
vars.x_2 = x_2;
vars.x{2} = x_2;
vars.x_3 = x_3;
vars.x{3} = x_3;
vars.x_4 = x_4;
vars.x{4} = x_4;
vars.x_5 = x_5;
vars.x{5} = x_5;
vars.x_6 = x_6;
vars.x{6} = x_6;
vars.x_7 = x_7;
vars.x{7} = x_7;
vars.x_8 = x_8;
vars.x{8} = x_8;
vars.x_9 = x_9;
vars.x{9} = x_9;
vars.x_10 = x_10;
vars.x{10} = x_10;
vars.x_11 = x_11;
vars.x{11} = x_11;
status.cvx_status = cvx_status;
% Provide a drop-in replacement for csolve.
status.optval = cvx_optval;
status.converged = strcmp(cvx_status, 'Solved');
